### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by mei-li** [mei-li/tsougkrizo#42]
Make the website  switchable greek/english with possibility to add more languages

# Subtasks:

- [x]  Move all text outside of template files and show them via JS. (Make separate task)
- [x] Find library to do this. Would https://github.com/wikimedia/jquery.i18n be a good candidate?
- [x] Use library to show text
- [x] Provide translation of all text in English
- [x] Provide translation of all text in Romanian (In Romania it seems the game is played also with passion)
- [x] Make the logos also internationalized. (make separate task)

**Comment by mei-li** [comment]
Task done, together with Fotis and Mano
